Default: &defaults
  host: "*4" # any IPv4 host
  port: 8181
  approot: "http://shared.computer-mind.com:8181"
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE
  aboutmessage: Esto es un texto de ejemplo.
  sitemail: notifyme@computer-mind.com
  dotasksgrantedips: 127.0.0.1
  
Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  port: 80
  approot: "http://tutorial-yesod-haskell.computer-mind.com"
  dotasksgrantedips: 37.235.53.89
  sitemail: notifyme@computer-mind.com
  <<: *defaults
