Default: &defaults
  database: NotifyMe.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: NotifyMe_test.sqlite3
  <<: *defaults

Staging:
  database: NotifyMe_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: NotifyMe_production.sqlite3
  poolsize: 100
  <<: *defaults
